version: '3'
services:
    broker:
        image: rabbitmq:management-alpine

    pv_sim:
        build: .
        command: python3 pv/pv.py
    grid:
        build: .
        command: python3 grid/grid.py
